-   id: nox
    name: nox
    description: ''
    entry: nox
    language: python
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
